max_lr: 0.005
weight_decay: 0.0005
momentum: 0.0
max_epochs: 200
batch_size: 4

use_pretrained_weights: true
pretrained_weights_path: /work/baardrw/fasterrcnn_resnet50_fpn_coco_grayscale.pth

image_h: 128
image_w: 256

test_model: false
checkpoint_path: checkpoints/baseline_512x512.ckpt
early_stopping_patience: 10
num_workers: 16
check_val_every_n_epoch: 3
devices: auto
enable_progress_bar: true

wandb_project: fine_tune
wandb_experiment_name: correct_norm

# Root for pretraining dataset /work/baardrw/cityscapesDataset

train_split_ratio: 0.8
pre_train: false
data_root: /datasets/tdt4265/ad/NAPLab-LiDAR
mode: fine
checkpoint_folder: /work/baardrw/checkpoints/nap/




