model: yolo

max_lr: 0.005
weight_decay: 0.0005
momentum: 0.9
max_epochs: 25
batch_size: 2
use_focal_loss: true

use_pretrained_weights: true
pretrained_weights_path: /work/ianma/yolo5m.pt

image_h: 128
image_w: 512
progressive_resizing: false
progressive_resizing_start_index: 0

test_model: false
# checkpoint_path: checkpoints/baseline_512x512.ckpt
early_stopping_patience: 10
num_workers: 16
check_val_every_n_epoch: 3
devices: auto
enable_progress_bar: true

wandb_project: yolo
wandb_experiment_name: yolo_test

# Root for pretraining dataset /work/baardrw/cityscapesDataset

train_split_ratio: 0.8
pre_train: false
data_root: C:\Users\ianak\data\NAPLab-LiDAR
mode: fine
checkpoint_folder: /work/ianma/checkpoints/
