model: retina

max_lr: 0.01
weight_decay: 0.001
momentum: 0.9
max_epochs: 100
batch_size: 12
use_focal_loss: false

staged_training: false
head_max_lr: 0.005
head_max_epochs: 20
all_max_lr: 0.002
all_max_epochs: 25


use_pretrained_weights: false
pretrained_weights_path: /work/baardrw/fasterrcnn_resnet50_fpn_coco_grayscale.pth

image_h: 256
image_w: 1024
progressive_resizing: false
progressive_resizing_start_index: 1

#/work/baardrw/checkpoints/fine_tune/porg_res_wout_focal_loss/prog_res0.ckpt
# checkpoints/baseline_512x512.ckpt
# /work/baardrw/checkpoints/fine_tune/no_focal_no_prog_resiz_hilr/best_model:epoch=17-val_map_50=0.2323.ckpt
test_model: false
checkpoint_path: #checkpoints/baseline_512x512.ckpt
early_stopping_patience: 10
num_workers: 16
check_val_every_n_epoch: 3
devices: auto
enable_progress_bar: true

wandb_project: Retina
wandb_experiment_name: base

# Root for pretraining dataset /work/baardrw/cityscapesDataset

train_split_ratio: 0.8
pre_train: true
data_root:  /work/ianma/cityscapes
mode: fine
checkpoint_folder: /work/ianma/checkpoints/
