model: retina

max_lr: 0.01
weight_decay: 0.001
momentum: 0.9
max_epochs: 25
batch_size: 16

use_focal_loss: false
use_custom_anchor_gen: false

staged_training: false
head_max_lr: 0.01
head_max_epochs: 30
all_max_lr: 0.005
all_max_epochs: 20


use_pretrained_weights: false
pretrained_weights_path: /work/ianma/fasterrcnn_resnet50_fpn_coco_grayscale.pth

image_h: 128
image_w: 256
progressive_resizing: false
progressive_resizing_start_index: 0

#/work/baardrw/checkpoints/fine_tune/porg_res_wout_focal_loss/prog_res0.ckpt
# 
# /work/baardrw/checkpoints/fine_tune/no_focal_no_prog_resiz_hilr/best_model:epoch=17-val_map_50=0.2323.ckpt
test_model: true
checkpoint_path: /work/ianma/checkpoints/Retina/staged_2_new_checkpoint/retina_final.ckpt
# /work/ianma/checkpoints/Retina/staged/best_model:epoch=02-val_map_50=0.2194.ckpt
early_stopping_patience: 10
num_workers: 20
check_val_every_n_epoch: 3
devices: auto
enable_progress_bar: true

wandb_project: Retina
wandb_experiment_name: sahi_test

# Root for pretraining dataset /work/baardrw/cityscapesDataset

train_split_ratio: 0.8
pre_train: false
data_root: /work/datasets/tdt4265/ad/NAPLab-LiDAR  
# /work/ianma/nap
mode: fine
checkpoint_folder: /work/ianma/checkpoints/
